#!/bin/bash
 # Shell script: temp.sh
 # Author: N1ghtGu4rd
cat .oculto
while true in
do
clear
  echo -e "\e[92mScript realizado por N1ghtGu4rd\e[0m"
  cpu=$(cat /sys/class/thermal/thermal_zone0/temp)
  echo -e "\e[92mEquipo => $(hostname)\e[0m"
  echo -e "\e[92m$(date)\e[0m"
  echo -e "\e[92m------------------------------\e[0m"
  echo -e "\e[92mTemp.CPU => $((cpu/1000))ºC\e[0m"
  echo -e "\e[92mTemp.GPU => Solo disponible para Raspberri PI4\e[0m"
  echo -e "\e[92m------------------------------\e[0m"
  echo -e "\e[92mConsumo de memoria\e[0m"
  echo -e "\e[92m$(egrep --color 'Mem|Cache|Swap' /proc/meminfo)\e[0m"
  sleep 2
done
